import { Theme } from "@/types/database";

export const defaultThemes: Theme[] = [
  {
    id: "oled-obsidian",
    name: "OLED Obsidian",
    category: "Monochrome & True Black",
    description: "Pure #000000 true-black canvas with crisp monochrome white accents and subtle titanium borders.",
    background: "#000000",
    foreground: "#ededed",
    card_bg: "rgba(9, 9, 11, 0.75)",
    border_color: "rgba(39, 39, 42, 0.8)",
    primary: "#ffffff",
    accent: "#a1a1aa",
    glow_color: "rgba(255, 255, 255, 0.15)",
    is_active: true,
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    category: "Atmospheric & Neon",
    description: "Deep midnight Japanese indigo canvas with vivid electric blue, neon cyan, and soft purple accents.",
    background: "#1a1b26",
    foreground: "#c0caf5",
    card_bg: "rgba(26, 27, 38, 0.82)",
    border_color: "rgba(65, 72, 104, 0.8)",
    primary: "#7aa2f7",
    accent: "#bb9af7",
    glow_color: "rgba(122, 162, 247, 0.3)",
    is_active: false,
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    category: "Pastel Dark & Cozy",
    description: "Comforting dark roast crust with soothing mauve, sapphire, and pastel peach developer aesthetics.",
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    card_bg: "rgba(30, 30, 46, 0.82)",
    border_color: "rgba(69, 71, 90, 0.85)",
    primary: "#cba6f7",
    accent: "#89b4fa",
    glow_color: "rgba(203, 166, 247, 0.25)",
    is_active: false,
  },
  {
    id: "nord-aurora",
    name: "Nord Aurora",
    category: "Arctic & Clean",
    description: "Arctic polar night palette with cool frost cyan, glacial blues, and vibrant aurora green accents.",
    background: "#242933",
    foreground: "#eceff4",
    card_bg: "rgba(46, 52, 64, 0.85)",
    border_color: "rgba(67, 76, 94, 0.85)",
    primary: "#88c0d0",
    accent: "#a3be8c",
    glow_color: "rgba(136, 192, 208, 0.28)",
    is_active: false,
  },
  {
    id: "cyberpunk-2077",
    name: "Cyberpunk 2077",
    category: "High Voltage & Synth",
    description: "High-contrast dark terminal illuminated by acid green lasers, electric magenta, and neon yellow.",
    background: "#0a0d14",
    foreground: "#00ff9d",
    card_bg: "rgba(13, 17, 26, 0.85)",
    border_color: "rgba(0, 255, 157, 0.35)",
    primary: "#00ff9d",
    accent: "#ff007f",
    glow_color: "rgba(0, 255, 157, 0.32)",
    is_active: false,
  },
  {
    id: "emerald-matrix",
    name: "Emerald Matrix",
    category: "Forest & Cryptography",
    description: "Deep cryptographic obsidian background paired with radiant emerald and cybernetic jade glow.",
    background: "#05130d",
    foreground: "#d1fae5",
    card_bg: "rgba(6, 26, 17, 0.82)",
    border_color: "rgba(16, 185, 129, 0.32)",
    primary: "#10b981",
    accent: "#34d399",
    glow_color: "rgba(16, 185, 129, 0.28)",
    is_active: false,
  },
  {
    id: "nebula-violet",
    name: "Nebula Violet",
    category: "Cosmic & Deep Space",
    description: "Deep cosmic dark violet canvas infused with electric ultraviolet, purple nebula, and fuchsia flare.",
    background: "#0d071e",
    foreground: "#e9d5ff",
    card_bg: "rgba(20, 10, 42, 0.85)",
    border_color: "rgba(139, 92, 246, 0.35)",
    primary: "#a855f7",
    accent: "#d946ef",
    glow_color: "rgba(168, 85, 247, 0.28)",
    is_active: false,
  },
  {
    id: "sunset-amber",
    name: "Sunset Amber",
    category: "Warm Titanium & Ember",
    description: "Warm espresso dark background glowing with golden amber, volcanic tangerine, and flame gradients.",
    background: "#140d07",
    foreground: "#fef3c7",
    card_bg: "rgba(28, 18, 10, 0.85)",
    border_color: "rgba(245, 158, 11, 0.3)",
    primary: "#f59e0b",
    accent: "#fb923c",
    glow_color: "rgba(245, 158, 11, 0.28)",
    is_active: false,
  },
];
